### ISSUE TITLE
cannot compile with openlava-3.0

### ISSUE THREAD

**Issue by gibiansky** [irvined1982/openlava-python#2]
```
In file included from /opt/openlava-3.0/include/lsbatch.h:26:0,
                 from openlava/lsblib.c:242:
/opt/openlava-3.0/include/lsf.h:19:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #define _GNU_SOURCE
 ^
In file included from /usr/include/python2.7/pyconfig.h:3:0,
                 from /usr/include/python2.7/Python.h:8,
                 from openlava/lsblib.c:4:
/usr/include/x86_64-linux-gnu/python2.7/pyconfig.h:1160:0: note: this is the location of the previous definition
 #define _GNU_SOURCE 1
 ^
openlava/lsblib.c: In function ‚Äò__pyx_pf_8openlava_6lsblib_9JobMsgLog_5usrId___get__‚Äô:
openlava/lsblib.c:45961:55: error: ‚Äòstruct jobMsgLog‚Äô has no member named ‚ÄòusrId‚Äô
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->_data->usrId); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4512; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                       ^
openlava/lsblib.c: In function ‚Äò__pyx_pf_8openlava_6lsblib_9JobMsgLog_5msgId___get__‚Äô:
openlava/lsblib.c:46087:55: error: ‚Äòstruct jobMsgLog‚Äô has no member named ‚ÄòmsgId‚Äô
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->_data->msgId); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4522; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                       ^
openlava/lsblib.c: In function ‚Äò__pyx_pf_8openlava_6lsblib_9JobMsgLog_4type___get__‚Äô:
openlava/lsblib.c:46150:55: error: ‚Äòstruct jobMsgLog‚Äô has no member named ‚Äòtype‚Äô
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->_data->type); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4527; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                       ^
openlava/lsblib.c: In function ‚Äò__pyx_pf_8openlava_6lsblib_9JobMsgLog_3src___get__‚Äô:
openlava/lsblib.c:46214:59: error: ‚Äòstruct jobMsgLog‚Äô has no member named ‚Äòsrc‚Äô
   __pyx_t_1 = __Pyx_PyBytes_FromString(__pyx_v_self->_data->src); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4532; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                           ^
openlava/lsblib.c: In function ‚Äò__pyx_pf_8openlava_6lsblib_9JobMsgLog_4dest___get__‚Äô:
openlava/lsblib.c:46282:59: error: ‚Äòstruct jobMsgLog‚Äô has no member named ‚Äòdest‚Äô
   __pyx_t_1 = __Pyx_PyBytes_FromString(__pyx_v_self->_data->dest); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4537; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                           ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

Is this an issue with my config or is this just because openlava 3.0 isn't supported? (looks like there was some strange encoding issue copy/pasting the single quotes, sorry about that)

**Comment by xeda-srobidas** [comment]
I couldn't compile with openlava 3 either, although I am using openlava 3.1.

I fixed my issue by making three modifications to setup.py:

First, add this import statement:
from Cython.Build import cythonize

Second, modify lsfdir in the try..catch statement as follows:
try:
    lsfdir=os.environ['LSF_ENVDIR']
    #The following line had a typo
    lsfdir=os.path.join(lsfdir,"..")

except:
    lsfdir='/opt/openlava/'

Third, modify the ext_modules argument in the setup() function call as follows:
ext_modules = cythonize( [makeExtension(name) for name in scandir("openlava")] )

Now, you must call setup.py differently. Use this command:
python setup.py build_ext --inplace

This worked for me, and hopefully it will work for you as well.
